Repository hcsp/make-method-generic, pull requests merged in 2020-02, with the labels that each got.

#37 编写泛型化的方法
  src/main/java/com/github/hcsp/generics/Main.java
Labels: is:answer

#38 完成编写泛型化的方法
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#39 修改测试类的第十一行代码的方法，传入的参数与第十行代码重复了
  src/test/java/com/github/hcsp/generics/MainTest.java
Labels: from:VIP, is:enhancement

#40 Make method generic.
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#41 灵活的泛型抵消了严格的类型检查带来所的负面
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#42 编写泛型化的方法
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#43 Wangyujie
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#44 make-method-generic
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#45 泛型练习
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer

#46 编写泛型化的方法
  src/main/java/com/github/hcsp/generics/Main.java
Labels: from:VIP, is:answer
